// This file is automatically generated by CMake using the version.in template,
// based on data obtained from the GenerateVersion.cmake script.

#	define VI_TM_VERSION_MAJOR 0
#	define VI_TM_VERSION_MINOR 1
#	define VI_TM_VERSION_PATCH 9
#	define VI_TM_GIT_DESCRIBE "v0.1.9-2-g26b8a77-dirty"
#	define VI_TM_GIT_COMMIT "26b8a772c088033123eea8dd3c4b9cf311ca6127"
#	define VI_TM_GIT_DATETIME "2025-09-26 18:23:47 +0300"
