// This file is automatically generated by CMake using the version.in template,
// based on data obtained from the GenerateVersion.cmake script.

#	define VI_TM_VERSION_MAJOR 0
#	define VI_TM_VERSION_MINOR 1
#	define VI_TM_VERSION_PATCH 9
#	define VI_TM_GIT_DESCRIBE "v0.1.9-1-g121c751-dirty"
#	define VI_TM_GIT_COMMIT "121c7519973543b21738fc4c7721e8c598fda6d7"
#	define VI_TM_GIT_DATETIME "2025-09-23 21:04:15 +0300"
