function(make_name_suffix OUT_VAR)
	set(_flags "")

	if(VI_TM_STAT_USE_RAW)
		string(APPEND _flags "r")
	endif()
	if(VI_TM_STAT_USE_FILTER)
		string(APPEND _flags "f")
	endif()
	if(VI_TM_STAT_USE_MINMAX)
		string(APPEND _flags "m")
	endif()
	if(VI_TM_THREADSAFE)
		string(APPEND _flags "t")
	endif()
	if(VI_TM_SHARED)
		string(APPEND _flags "s")
	endif()

	set(${OUT_VAR} ${_flags} PARENT_SCOPE)
endfunction()
